### ISSUE TITLE
[wrapacker] packer binary

### ISSUE THREAD

**Issue by joksnet** [elasticdog/packer-arch#39]
ArchLinux have a wrapper for pacman called packer, so the AUR package [packer-io](https://aur.archlinux.org/packages/packer-io/) will be installed in `/usr/bin/packer-io`.

Would be nice if the wrapacker look for the right binary.

**Comment by elasticdog** [comment]
Thanks for reporting this! I pretty much always run Packer from my OS X machine, so I didn't realize that there was a naming conflict for the `packer` binary on Arch itself.
