### ISSUE TITLE
Timeout waiting for SSH

### ISSUE THREAD

**Issue by PaulWalkerUK** [elasticdog/packer-arch#63]
I'm trying to build this with `packer build -only=virtualbox-iso arch-template.json`, but it times out waiting for SSH:

```
==> virtualbox-iso: Retrieving ISO
1 items:  586.00 MiB / 586.00 MiB  12m32s
    virtualbox-iso: Transferred: https://mirrors.kernel.org/archlinux/iso/2018.11.01/archlinux-2018.11.01-x86_64.iso
==> virtualbox-iso: Starting HTTP server on port 8765
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 3719)
==> virtualbox-iso: Starting the virtual machine...
==> virtualbox-iso: Waiting 5s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Using ssh communicator to connect: 127.0.0.1
==> virtualbox-iso: Waiting for SSH to become available...
==> virtualbox-iso: Timeout waiting for SSH.
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Timeout waiting for SSH.

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Timeout waiting for SSH.

==> Builds finished but no artifacts were created.
```

**Comment by appleby** [comment]
Try running the build with the included `wrapacker` script, which sets the timeout (and other defaults) automatically. See `./wrapacker -h` for usage, or `./wrapacker -d` for a dry-run that just prints the `packer build` command that would be invoked by `wrapacker`.

Alternatively, you could try adding `-var 'ssh_timeout=20m'` (or whatever timeout you want) to your `packer build` command.

**Comment by PaulWalkerUK** [comment]
It's OK, think I've I've sorted it. Looks like I needed to increase the delay before running the `enable-ssh.sh` script. For the sake of getting it to work, I've increased both the `boot-wait` time and added more `<wait10>`, though with testing, I might be able to revise one or the other back down.

Thanks for your help
